/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prometheus metrics
         * @description Requires an ADMIN or OPERATOR bearer principal.
         */
        get: operations["getMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/formalizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an immutable candidate formalization */
        post: operations["createFormalization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/formalizations/{formalization_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the current or selected immutable revision */
        get: operations["getFormalization"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/formalizations/{formalization_id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Append a replacement content revision */
        post: operations["reviseFormalization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/formalizations/{formalization_id}/validations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record deterministic structural validation */
        post: operations["validateFormalization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/formalizations/{formalization_id}/confirmations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record human confirmation after successful validation */
        post: operations["confirmFormalization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/formalizations/{formalization_id}/rejections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record an explicit human rejection */
        post: operations["rejectFormalization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a fully bound draft session
         * @description Requires an ADMIN or RESEARCHER bearer principal.
         */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a fully bound draft session */
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/events/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream committed session events from the authoritative ledger
         * @description Replays rows after Last-Event-ID or since, then uses NATS only as a wake-up for new ledger reads.
         */
        get: operations["streamSessionEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Idempotently start durable session execution
         * @description Requires an ADMIN or RESEARCHER bearer principal.
         */
        post: operations["startSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enqueue an idempotent session pause
         * @description Requires an ADMIN or RESEARCHER bearer principal. The returned session is the current PostgreSQL projection; poll the session resource for the interpreted transition.
         */
        post: operations["pauseSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enqueue an idempotent session resume
         * @description Requires an ADMIN or RESEARCHER bearer principal.
         */
        post: operations["resumeSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enqueue idempotent terminal cancellation
         * @description Requires an ADMIN or RESEARCHER bearer principal. Cancellation never deletes session history.
         */
        post: operations["cancelSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/terminate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enqueue cancellation through the legacy termination path
         * @deprecated
         * @description Compatibility alias for cancelSession. It records SESSION_CANCELLED and never deletes history.
         */
        post: operations["terminateSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/human-input": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enqueue a validated human directive
         * @description Requires an ADMIN or RESEARCHER bearer principal. The workflow records the directive as a HUMAN-authored ledger event.
         */
        post: operations["submitHumanInput"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Commit an initial reasoning artifact
         * @description Requires an ADMIN or RESEARCHER bearer principal.
         */
        post: operations["createArtifact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a reasoning artifact revision */
        get: operations["getArtifact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/{artifact_id}/provenance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read bounded reasoning ancestry and canonical evidence citations */
        get: operations["getArtifactProvenance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/{artifact_id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Commit a complete replacement artifact revision
         * @description Requires an ADMIN or RESEARCHER bearer principal.
         */
        post: operations["reviseArtifact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/artifacts/{artifact_id}/withdrawals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Withdraw an artifact without deletion
         * @description Requires an ADMIN or RESEARCHER bearer principal and at least one warrant.
         */
        post: operations["withdrawArtifact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{source_id}/retractions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retract a source and atomically publish its durable impact report
         * @description Requires an ADMIN or RESEARCHER bearer principal.
         */
        post: operations["retractSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/impact-reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read an immutable source-impact report */
        get: operations["getImpactReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SessionId: string;
        ArtifactId: string;
        FormalizationId: string;
        /** @enum {string} */
        ValidationStatus: "CANDIDATE" | "VALIDATED" | "REJECTED";
        SymbolDeclaration: {
            name: string;
            /** @enum {string} */
            sort: "BOOLEAN" | "INTEGER" | "REAL";
            meaning: string;
            unit: string | null;
        };
        /** @description Closed typed AST. Unknown nodes and operators are rejected. */
        FormalAST: components["schemas"]["FormalBoolean"] | components["schemas"]["FormalInteger"] | components["schemas"]["FormalReal"] | components["schemas"]["FormalSymbol"] | components["schemas"]["FormalOperation"];
        FormalBoolean: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "FormalBoolean";
            value: boolean;
        };
        FormalInteger: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "FormalInteger";
            value: string;
        };
        FormalReal: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "FormalReal";
            value: string;
        };
        FormalSymbol: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "FormalSymbol";
            name: string;
        };
        FormalOperation: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "FormalOperation";
            /** @enum {string} */
            operator: "NOT" | "AND" | "OR" | "NEG" | "ADD" | "SUB" | "MUL" | "DIV" | "EQ" | "NE" | "LT" | "LE" | "GT" | "GE";
            arguments: components["schemas"]["FormalAST"][];
        };
        FormalizationCreate: {
            source_artifact_id: components["schemas"]["ArtifactId"];
            ast: components["schemas"]["FormalAST"];
            symbols: components["schemas"]["SymbolDeclaration"][];
            canonical_rendering: string;
            premise_artifact_ids: components["schemas"]["ArtifactId"][];
            limitations: string[];
            fidelity_notes: string;
        };
        FormalizationDecisionCreate: {
            reason: string;
        };
        FormalizationResponse: {
            data: {
                id: components["schemas"]["FormalizationId"];
                revision_id: components["schemas"]["FormalizationId"];
                revision: number;
                ast: components["schemas"]["FormalAST"];
                ast_hash: string;
                validation_status: components["schemas"]["ValidationStatus"];
                enforceable: boolean;
            } & {
                [key: string]: unknown;
            };
            meta: {
                [key: string]: unknown;
            };
        };
        SourceId: string;
        ImpactReportId: string;
        SourceRetractionId: string;
        ConsensusResultId: string;
        RecommendationId: string;
        AgentId: string;
        WorkspaceId: string;
        /** @enum {string} */
        ArtifactKind: "CLAIM" | "FACT" | "ASSUMPTION" | "INFERENCE" | "PROPOSITION" | "EVIDENCE" | "UNCERTAINTY" | "RISK" | "IMPACT" | "OBJECTIVE" | "CONSTRAINT" | "ALTERNATIVE" | "POSITION" | "CRITIQUE";
        /** @enum {string} */
        LifecycleStatus: "ACTIVE" | "SUPERSEDED" | "WITHDRAWN";
        /** @enum {string} */
        ActorClass: "HUMAN" | "AGENT" | "SERVICE" | "POLICY";
        /** @enum {string} */
        ProvenanceOrigin: "HUMAN" | "LLM" | "RETRIEVAL" | "TOOL" | "SIMULATION" | "SYMBOLIC" | "IMPORT" | "HISTORICAL_SESSION";
        /** @enum {string} */
        GraphEdgeType: "SUPPORTS" | "OPPOSES" | "CONTRADICTS" | "DERIVED_FROM" | "BASED_ON_ASSUMPTION" | "FORMALIZES" | "QUANTIFIES" | "IMPACTS" | "CONSTRAINS" | "VIOLATES" | "SATISFIES" | "INFEASIBLE_UNKNOWN" | "ATTACKS" | "RESPONDS_TO" | "SUPERSEDES" | "ADVOCATES";
        ProvenanceInput: {
            origin: components["schemas"]["ProvenanceOrigin"];
            reference: string;
        };
        SourceReference: {
            reference: string;
            locator: {
                [key: string]: unknown;
            };
            content_hash: string;
            /** Format: date-time */
            retrieved_at: string;
            /** Format: date-time */
            source_timestamp?: string | null;
        };
        ParentRelationshipInput: {
            edge_type: components["schemas"]["GraphEdgeType"];
            target_artifact_id: components["schemas"]["ArtifactId"];
        };
        ConfidenceInput: {
            kind: string;
            value: string;
            meaning: string;
            basis_artifact_ids: components["schemas"]["ArtifactId"][];
        };
        ArtifactCreate: {
            kind: components["schemas"]["ArtifactKind"];
            /** @description Strictly validated against the selected Phase 3 artifact kind. */
            payload: {
                [key: string]: unknown;
            };
            provenance: components["schemas"]["ProvenanceInput"];
            source_references: components["schemas"]["SourceReference"][];
            parent_relationships: components["schemas"]["ParentRelationshipInput"][];
            confidence?: components["schemas"]["ConfidenceInput"] | null;
            metadata: {
                [key: string]: unknown;
            };
        };
        ArtifactRevisionCreate: {
            /** @description Complete replacement payload; kind and logical identity are server-owned. */
            payload: {
                [key: string]: unknown;
            };
            provenance: components["schemas"]["ProvenanceInput"];
            source_references: components["schemas"]["SourceReference"][];
            parent_relationships: components["schemas"]["ParentRelationshipInput"][];
            confidence?: components["schemas"]["ConfidenceInput"] | null;
            metadata: {
                [key: string]: unknown;
            };
            reason: string;
        };
        ArtifactWithdrawalCreate: {
            reason: string;
            warrant_artifact_ids: components["schemas"]["ArtifactId"][];
        };
        SessionBudget: {
            max_rounds: number;
            max_tokens: number;
            max_usd: string;
            /** Format: date-time */
            deadline_at?: string | null;
        };
        SessionCreate: {
            problem_statement: string;
            agent_definition_ids: components["schemas"]["AgentId"][];
            objectives: (components["schemas"]["ArtifactCreate"] & {
                /** @constant */
                kind?: "OBJECTIVE";
            })[];
            constraints: (components["schemas"]["ArtifactCreate"] & {
                /** @constant */
                kind?: "CONSTRAINT";
            })[];
            budget: components["schemas"]["SessionBudget"];
        };
        SessionControlCreate: {
            reason: string;
        };
        /** @enum {string} */
        HumanDirectiveKind: "INJECT_EVIDENCE" | "ADD_CONSTRAINT" | "MODIFY_OBJECTIVE" | "REQUEST_SIMULATION" | "REQUEST_CRITIQUE" | "REQUEST_ANOTHER_ROUND" | "REJECT_RECOMMENDATION" | "OVERRIDE_OUTCOME";
        HumanInputCreate: {
            reason: string;
            kind: components["schemas"]["HumanDirectiveKind"];
            instruction: string;
            /** @default [] */
            artifact_ids: components["schemas"]["ArtifactId"][];
        };
        ResourceOwner: {
            id: string;
            class: components["schemas"]["ActorClass"];
        };
        SessionData: {
            id: components["schemas"]["SessionId"];
            /** @enum {string} */
            status: "DRAFT" | "INITIALIZING" | "RUNNING" | "WAITING_FOR_AGENT" | "WAITING_FOR_EVIDENCE" | "WAITING_FOR_CRITIQUE" | "WAITING_FOR_SIMULATION" | "WAITING_FOR_HUMAN" | "EVALUATING_CONSENSUS" | "PAUSED" | "FAILED_RETRYABLE" | "COMPLETED" | "PARTIAL_CONSENSUS_STATE" | "NO_CONSENSUS" | "DEADLOCK" | "FAILED" | "CANCELLED";
            problem_statement: string;
            agent_definition_ids: components["schemas"]["AgentId"][];
            objective_ids: components["schemas"]["ArtifactId"][];
            constraint_ids: components["schemas"]["ArtifactId"][];
            budget: components["schemas"]["SessionBudget"];
            round: number;
            workflow_id: string | null;
            run_id: string | null;
            /** Format: date-time */
            initialized_at: string | null;
            /** Format: date-time */
            started_at: string | null;
            /** Format: date-time */
            ended_at: string | null;
        };
        SessionMeta: {
            request_id: string;
            /** @constant */
            schema_version: 1;
            /** @constant */
            version: 1;
            workspace_id: components["schemas"]["WorkspaceId"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            owner: components["schemas"]["ResourceOwner"];
            permissions: string[];
            trace: null;
        };
        SessionResponse: {
            data: components["schemas"]["SessionData"];
            meta: components["schemas"]["SessionMeta"];
        };
        /** @description Kind-specific payload. CLAIM always includes explicit unsupported boolean. */
        ArtifactAttributes: {
            unsupported?: boolean;
        } & {
            [key: string]: unknown;
        };
        ProvenanceState: {
            origin: components["schemas"]["ProvenanceOrigin"];
            reference: string;
            complete: boolean;
            missing: string[];
        };
        ArtifactData: {
            id: components["schemas"]["ArtifactId"];
            kind: components["schemas"]["ArtifactKind"];
            attributes: components["schemas"]["ArtifactAttributes"];
            source_references: components["schemas"]["SourceReference"][];
            parent_relationships: components["schemas"]["ParentRelationshipInput"][];
            confidence: components["schemas"]["ConfidenceInput"] | null;
            metadata: {
                [key: string]: unknown;
            };
            content_hash: string;
        };
        ArtifactMeta: {
            request_id: string;
            schema_version: number;
            version: number;
            workspace_id: components["schemas"]["WorkspaceId"];
            session_id: components["schemas"]["SessionId"];
            logical_id: components["schemas"]["ArtifactId"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            owner: components["schemas"]["ResourceOwner"];
            lifecycle_status: components["schemas"]["LifecycleStatus"];
            supersedes_id: components["schemas"]["ArtifactId"] | null;
            provenance: components["schemas"]["ProvenanceState"];
            permissions: string[];
            trace: null;
        };
        ArtifactResponse: {
            data: components["schemas"]["ArtifactData"];
            meta: components["schemas"]["ArtifactMeta"];
        };
        ProvenanceGraphNode: {
            id: string;
            workspace_id: components["schemas"]["WorkspaceId"];
            session_id: components["schemas"]["SessionId"];
            kind: components["schemas"]["ArtifactKind"];
            ref_id: components["schemas"]["ArtifactId"];
            label: string;
            attrs: {
                [key: string]: unknown;
            };
        };
        ProvenanceGraphEdge: {
            id: string;
            workspace_id: components["schemas"]["WorkspaceId"];
            session_id: components["schemas"]["SessionId"];
            from_node: string;
            to_node: string;
            edge_type: components["schemas"]["GraphEdgeType"];
            weight: number | null;
            qualifier: {
                [key: string]: unknown;
            };
            actor_class: components["schemas"]["ActorClass"];
            actor_id: string;
        };
        /** @description Immutable citation snapshot plus current source status and retraction metadata. */
        CitationResolution: {
            citation: {
                [key: string]: unknown;
            };
            /** @enum {string} */
            current_source_status: "PROCESSING" | "READY" | "FAILED" | "RETRACTED";
            /** Format: date-time */
            retracted_at: string | null;
            retraction_reason: string | null;
        } & {
            [key: string]: unknown;
        };
        ProvenanceNode: {
            graph_node: components["schemas"]["ProvenanceGraphNode"];
            artifact_version: number;
            /** @enum {string|null} */
            verification: "UNVERIFIED" | "SOURCE_VERIFIED" | "CROSS_CHECKED" | "DISPUTED" | "REJECTED" | null;
            citations: components["schemas"]["CitationResolution"][];
        };
        ProvenanceData: {
            root_artifact_id: components["schemas"]["ArtifactId"];
            root_artifact_version: number;
            root_node: components["schemas"]["ProvenanceGraphNode"];
            nodes: components["schemas"]["ProvenanceNode"][];
            edges: components["schemas"]["ProvenanceGraphEdge"][];
            truncated: boolean;
            max_depth: number;
            next_cursor: string | null;
        };
        ProvenanceResponse: {
            data: components["schemas"]["ProvenanceData"];
            meta: {
                request_id: string;
                workspace_id: components["schemas"]["WorkspaceId"];
            };
        };
        SourceRetractionCreate: {
            reason: string;
        };
        ImpactDependency: {
            /** @enum {string} */
            dependency_type: "ARTIFACT" | "CONSENSUS_RESULT" | "RECOMMENDATION";
            dependent_id: string;
            session_id: components["schemas"]["SessionId"];
            root_evidence_id: components["schemas"]["ArtifactId"];
            artifact_kind: components["schemas"]["ArtifactKind"] | null;
            logical_id: components["schemas"]["ArtifactId"] | null;
            artifact_version: number | null;
            min_depth: number;
            path_count: number;
            evidence_weight: string;
        };
        ImpactReportData: {
            id: components["schemas"]["ImpactReportId"];
            retraction_id: components["schemas"]["SourceRetractionId"];
            event_id: string;
            source_id: components["schemas"]["SourceId"];
            actor_id: string;
            reason: string;
            /** Format: date-time */
            generated_at: string;
            /** @enum {string} */
            analysis_status: "COMPLETE" | "INCOMPLETE";
            complete: boolean;
            truncated: boolean;
            error: string | null;
            dependencies: components["schemas"]["ImpactDependency"][];
            affected_claim_ids: components["schemas"]["ArtifactId"][];
            affected_alternative_ids: components["schemas"]["ArtifactId"][];
            affected_consensus_result_ids: components["schemas"]["ConsensusResultId"][];
            affected_recommendation_ids: components["schemas"]["RecommendationId"][];
        };
        ImpactReportResponse: {
            data: components["schemas"]["ImpactReportData"];
            meta: {
                request_id: string;
                workspace_id: components["schemas"]["WorkspaceId"];
            };
        };
        /** @enum {string} */
        HealthStatus: "ok" | "degraded" | "down" | "unknown";
        HealthResponse: {
            /** @constant */
            status: "ok";
            service: string;
            version: string;
        };
        ComponentHealth: {
            status: components["schemas"]["HealthStatus"];
            details: {
                [key: string]: unknown;
            };
        };
        ReadinessResponse: {
            status: components["schemas"]["HealthStatus"];
            service: string;
            version: string;
            components: {
                [key: string]: components["schemas"]["ComponentHealth"];
            };
        };
        ValidationIssue: {
            pointer: string;
            message: string;
            type: string;
        };
        /** @enum {string} */
        ErrorCode: "VALIDATION_FAILED" | "UNKNOWN_FIELD" | "AUTH_REQUIRED" | "FORBIDDEN" | "COMMIT_FORBIDDEN" | "VERSION_CONFLICT" | "IDEMPOTENCY_REPLAY" | "NOT_FOUND" | "PROVENANCE_MISSING" | "BUDGET_EXCEEDED" | "RATE_LIMITED" | "PORT_UNAVAILABLE" | "RAG_FAILED" | "WORKFLOW_UNREACHABLE" | "INTERNAL";
        ProblemDetails: {
            /** Format: uri */
            type: string;
            title: string;
            status: number;
            code: components["schemas"]["ErrorCode"];
            detail: string;
            instance?: string | null;
            trace_id?: string | null;
            retryable: boolean;
            errors?: components["schemas"]["ValidationIssue"][];
            current_version?: number;
            retry_after_s?: number;
            degraded?: string;
        };
    };
    responses: {
        /** @description The authoritative immutable formalization revision and derived status. */
        FormalizationRead: {
            headers: {
                ETag: components["headers"]["ETag"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["FormalizationResponse"];
            };
        };
        /** @description The formalization revision or lifecycle fact committed atomically. */
        FormalizationWritten: {
            headers: {
                ETag: components["headers"]["ETag"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["FormalizationResponse"];
            };
        };
        /** @description The durable workflow accepted the command. PostgreSQL remains authoritative for lifecycle state. */
        SessionControlAccepted: {
            headers: {
                ETag: components["headers"]["ETag"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["SessionResponse"];
            };
        };
        /** @description The durable workflow engine is unavailable. */
        WorkflowUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description A valid bearer token was not supplied. */
        AuthenticationRequired: {
            headers: {
                "WWW-Authenticate"?: "Bearer";
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description The verified principal is not allowed to use this route. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description The strict request or a domain invariant failed validation. */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description The resource is absent or hidden by tenant isolation. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description The entity version or idempotency request identity conflicts. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        SessionId: components["schemas"]["SessionId"];
        ArtifactId: components["schemas"]["ArtifactId"];
        SourceId: components["schemas"]["SourceId"];
        ImpactReportId: components["schemas"]["ImpactReportId"];
        IdempotencyKey: string;
        IfMatch: number;
        FormalizationId: components["schemas"]["FormalizationId"];
    };
    requestBodies: never;
    headers: {
        /** @description Current integer entity version. */
        ETag: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The API process is live. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The API can serve traffic; dependencies are healthy or degraded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description At least one required dependency is down. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    getMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prometheus text exposition. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["Forbidden"];
        };
    };
    createFormalization: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FormalizationCreate"];
            };
        };
        responses: {
            201: components["responses"]["FormalizationWritten"];
            400: components["responses"]["ValidationFailed"];
            409: components["responses"]["Conflict"];
        };
    };
    getFormalization: {
        parameters: {
            query?: {
                revision?: number;
            };
            header?: never;
            path: {
                formalization_id: components["parameters"]["FormalizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["FormalizationRead"];
            404: components["responses"]["NotFound"];
        };
    };
    reviseFormalization: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                formalization_id: components["parameters"]["FormalizationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FormalizationCreate"];
            };
        };
        responses: {
            201: components["responses"]["FormalizationWritten"];
            409: components["responses"]["Conflict"];
        };
    };
    validateFormalization: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                formalization_id: components["parameters"]["FormalizationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            201: components["responses"]["FormalizationWritten"];
            409: components["responses"]["Conflict"];
        };
    };
    confirmFormalization: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                formalization_id: components["parameters"]["FormalizationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FormalizationDecisionCreate"];
            };
        };
        responses: {
            201: components["responses"]["FormalizationWritten"];
            409: components["responses"]["Conflict"];
        };
    };
    rejectFormalization: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                formalization_id: components["parameters"]["FormalizationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FormalizationDecisionCreate"];
            };
        };
        responses: {
            201: components["responses"]["FormalizationWritten"];
            409: components["responses"]["Conflict"];
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionCreate"];
            };
        };
        responses: {
            /** @description The session, artifacts, graph projections, and ledger events committed atomically. */
            201: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant-visible session resource. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    streamSessionEvents: {
        parameters: {
            query?: {
                since?: number;
            };
            header?: {
                "Last-Event-ID"?: number;
            };
            path: {
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ledger-ordered Server-Sent Events. Each SSE id equals ledger_seq. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    startSession: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Temporal accepted the start and its execution identity was persisted. */
            202: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            /** @description The durable workflow engine is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    pauseSession: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionControlCreate"];
            };
        };
        responses: {
            202: components["responses"]["SessionControlAccepted"];
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["WorkflowUnavailable"];
        };
    };
    resumeSession: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionControlCreate"];
            };
        };
        responses: {
            202: components["responses"]["SessionControlAccepted"];
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["WorkflowUnavailable"];
        };
    };
    cancelSession: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionControlCreate"];
            };
        };
        responses: {
            202: components["responses"]["SessionControlAccepted"];
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["WorkflowUnavailable"];
        };
    };
    terminateSession: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionControlCreate"];
            };
        };
        responses: {
            202: components["responses"]["SessionControlAccepted"];
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["WorkflowUnavailable"];
        };
    };
    submitHumanInput: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HumanInputCreate"];
            };
        };
        responses: {
            202: components["responses"]["SessionControlAccepted"];
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["WorkflowUnavailable"];
        };
    };
    createArtifact: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArtifactCreate"];
            };
        };
        responses: {
            /** @description Artifact, graph projection, and ledger event committed atomically. */
            201: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: components["parameters"]["ArtifactId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant-visible artifact with explicit epistemic and provenance state. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactResponse"];
                };
            };
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getArtifactProvenance: {
        parameters: {
            query?: {
                max_depth?: number;
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path: {
                artifact_id: components["parameters"]["ArtifactId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bounded graph ancestry enriched with canonical citation resolution. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvenanceResponse"];
                };
            };
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    reviseArtifact: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                artifact_id: components["parameters"]["ArtifactId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArtifactRevisionCreate"];
            };
        };
        responses: {
            /** @description New active revision; predecessor is retained as superseded. */
            201: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    withdrawArtifact: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                artifact_id: components["parameters"]["ArtifactId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArtifactWithdrawalCreate"];
            };
        };
        responses: {
            /** @description Artifact lifecycle is withdrawn; immutable content remains available. */
            200: {
                headers: {
                    ETag: components["headers"]["ETag"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    retractSource: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                source_id: components["parameters"]["SourceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceRetractionCreate"];
            };
        };
        responses: {
            /** @description Source state, exact dependency snapshot, report, and workspace event committed atomically without mutating downstream artifacts. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImpactReportResponse"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getImpactReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: components["parameters"]["ImpactReportId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tenant-visible immutable impact report. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImpactReportResponse"];
                };
            };
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
}
