"""UUIDv7 generation and prefixed resource identifiers.

Contract: `memory-bank/techContext.md` §3 — "IDs: UUIDv7 (time-ordered) for entity and
event identifiers." `docs/PORTS.md` §0 — ids are generated by the **caller**, never by an
adapter, so a replay produces the same identifiers.

`uuid7` is implemented here rather than taken from a library because the standard library
does not provide it on the supported Python floor (3.12).
"""

from __future__ import annotations

import secrets
import time
import uuid

__all__ = ["ID_PREFIXES", "new_id", "parse_id", "public_id", "uuid7"]

# Resource prefixes, from docs/API.md. Kept in one place so a typo in a prefix is a
# lookup error rather than a silently malformed identifier.
ID_PREFIXES: dict[str, str] = {
    "workspace": "ws",
    "user": "usr",
    "session": "ses",
    "artifact": "art",
    "agent": "agt",
    "round": "rnd",
    "event": "evt",
    "evidence": "evi",
    "proposition": "prp",
    "critique": "crt",
    "recommendation": "rec",
    "consensus_result": "csr",
    "service": "svc",
    "policy": "pol",
    "document": "doc",
    "chunk": "chk",
    "source": "src",
    "namespace": "kns",
    "citation": "cit",
    "impact_report": "imr",
    "source_retraction": "srt",
    "graph_node": "gnd",
    "graph_edge": "ged",
    "experiment": "exp",
    "formalization": "frm",
    "symbolic_evaluation": "sev",
    "run": "run",
    "manifest": "man",
    "replay_step": "rps",
    "replay_result": "rpr",
}


def uuid7(now_ms: int | None = None) -> uuid.UUID:
    """Return an RFC 9562 UUIDv7: 48-bit ms timestamp, 74 bits of randomness.

    `now_ms` is injectable so that a test — or a replay — can pin the clock. Passing an
    explicit value is the only supported way to make identifiers deterministic; the
    random fields are never derived from the payload.
    """
    ms = int(time.time() * 1000) if now_ms is None else now_ms
    if not 0 <= ms < 1 << 48:
        raise ValueError(f"timestamp does not fit in 48 bits: {ms}")

    rand = secrets.randbits(74)
    rand_a = (rand >> 62) & 0x0FFF
    rand_b = rand & ((1 << 62) - 1)

    value = (ms & 0xFFFFFFFFFFFF) << 80  # unix_ts_ms
    value |= 0x7 << 76  # version 7
    value |= rand_a << 64  # rand_a
    value |= 0b10 << 62  # variant 1 (RFC 4122 layout)
    value |= rand_b  # rand_b
    return uuid.UUID(int=value)


def new_id(resource: str, *, now_ms: int | None = None) -> str:
    """Return a prefixed identifier such as ``ses_01h...`` for a known resource kind."""
    try:
        prefix = ID_PREFIXES[resource]
    except KeyError as exc:  # pragma: no cover - programmer error
        raise KeyError(
            f"unknown resource {resource!r}; add it to ID_PREFIXES (known: "
            f"{', '.join(sorted(ID_PREFIXES))})"
        ) from exc
    return f"{prefix}_{uuid7(now_ms).hex}"


def public_id(resource: str, value: uuid.UUID) -> str:
    """Encode an internal UUID as the reviewed opaque API identifier."""
    try:
        prefix = ID_PREFIXES[resource]
    except KeyError as exc:
        raise KeyError(f"unknown resource {resource!r}") from exc
    return f"{prefix}_{value.hex}"


def parse_id(resource: str, value: str) -> uuid.UUID:
    """Decode one correctly prefixed public identifier without accepting bare UUIDs."""
    try:
        prefix = ID_PREFIXES[resource]
    except KeyError as exc:
        raise KeyError(f"unknown resource {resource!r}") from exc
    expected = f"{prefix}_"
    if not value.startswith(expected):
        raise ValueError(f"expected a {prefix}_ identifier")
    body = value[len(expected) :]
    if len(body) != 32 or body.lower() != body:
        raise ValueError(f"expected a canonical {prefix}_ identifier")
    try:
        parsed = uuid.UUID(hex=body)
    except ValueError as exc:
        raise ValueError(f"expected a canonical {prefix}_ identifier") from exc
    if resource not in {"manifest", "replay_step"} and parsed.version != 7:
        raise ValueError(f"expected a UUIDv7 {prefix}_ identifier")
    return parsed
